# Generated by Django 4.2.13 on 2024-08-15 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_task_image_task_link_task_time_alter_task_priority_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Active', 'active'), ('Inactive', 'inactive'), ('Archived', 'archived')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('Low', 'low'), ('Medium', 'medium'), ('High', 'high'), ('God Dammit', 'gd')], default='medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('To Do', 'todo'), ('In Progress', 'in_progress'), ('Done', 'done'), ('Ideas', 'ideas')], default='todo', max_length=20),
        ),
    ]
