# Generated by Django 4.2.13 on 2024-08-15 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_alter_project_status_alter_task_priority_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('To-Do', 'todo'), ('In Progress', 'in_progress'), ('Done', 'done'), ('Ideas', 'ideas')], default='todo', max_length=20),
        ),
    ]
