# Generated by Django 4.2.13 on 2024-08-21 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0007_task_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='user',
            new_name='creator_of_project',
        ),
    ]
