# Generated by Django 4.2.13 on 2024-08-21 15:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('system', '0008_rename_user_project_creator_of_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='members',
            field=models.ManyToManyField(blank=True, null=True, related_name='member', to=settings.AUTH_USER_MODEL),
        ),
    ]
