# Generated by Django 4.2.13 on 2024-08-24 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0015_remove_project_image_alter_task_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='image',
        ),
    ]
