# Generated by Django 4.2.13 on 2024-08-29 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0018_project_files_task_files_alter_project_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='pr_media'),
        ),
    ]
